// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMDs9S4hM85idzCromg6UoAxkBefOi4s',
    appId: '1:943215173298:web:6ee3ed4bc50ccbe58673ab',
    messagingSenderId: '943215173298',
    projectId: 'trekwise-final',
    authDomain: 'trekwise-final.firebaseapp.com',
    storageBucket: 'trekwise-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdKwOXE2Kvltul75DycoNFj9VfymdhrrM',
    appId: '1:943215173298:android:a128a4de1e2492c58673ab',
    messagingSenderId: '943215173298',
    projectId: 'trekwise-final',
    storageBucket: 'trekwise-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTaInQZ8Cz4Zr18b0pWa1XQI4J4f7lzk',
    appId: '1:943215173298:ios:4de882bbe7196f198673ab',
    messagingSenderId: '943215173298',
    projectId: 'trekwise-final',
    storageBucket: 'trekwise-final.firebasestorage.app',
    iosBundleId: 'com.example.trekwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbTaInQZ8Cz4Zr18b0pWa1XQI4J4f7lzk',
    appId: '1:943215173298:ios:4de882bbe7196f198673ab',
    messagingSenderId: '943215173298',
    projectId: 'trekwise-final',
    storageBucket: 'trekwise-final.firebasestorage.app',
    iosBundleId: 'com.example.trekwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATMDs9S4hM85idzCromg6UoAxkBefOi4s',
    appId: '1:943215173298:web:91a3296620d469328673ab',
    messagingSenderId: '943215173298',
    projectId: 'trekwise-final',
    authDomain: 'trekwise-final.firebaseapp.com',
    storageBucket: 'trekwise-final.firebasestorage.app',
  );

}